/* Foto Shop Estudio — data.js
   Generado desde el panel de administración */

const FEATURED_CLIENT = 'TRICOT';

const PHOTOS = [
  { id: 41, src: 'photos/lenceria/13273-241_1.jpg', category: 'lenceria', categoryLabel: 'Lencería', client: 'Flores', title: '' },
  { id: 42, src: 'photos/lenceria/25488-2-1.jpg', category: 'lenceria', categoryLabel: 'Lencería', client: 'Flores', title: '' },
  { id: 43, src: 'photos/lenceria/9683-1-5.jpg', category: 'lenceria', categoryLabel: 'Lencería', client: 'Flores', title: '' },
  { id: 44, src: 'photos/lenceria/9683-2-5.jpg', category: 'lenceria', categoryLabel: 'Lencería', client: 'Flores', title: '' },
  { id: 45, src: 'photos/lenceria/25486-2-1.jpg', category: 'lenceria', categoryLabel: 'Lencería', client: 'Flores', title: '' },
  { id: 46, src: 'photos/lenceria/90000-94-2.jpg', category: 'lenceria', categoryLabel: 'Lencería', client: 'Flores', title: '' },
  { id: 47, src: 'photos/lenceria/90003-1-3.jpg', category: 'lenceria', categoryLabel: 'Lencería', client: 'Flores', title: '' },
  { id: 48, src: 'photos/lenceria/grupo-ana-y-gaby-2.jpg', category: 'lenceria', categoryLabel: 'Lencería', client: 'Flores', title: '' },
  { id: 49, src: 'photos/lenceria/25511-172-1.jpg', category: 'lenceria', categoryLabel: 'Lencería', client: 'Flores', title: '' },
  { id: 50, src: 'photos/infantil/01-2025-14.jpg', category: 'infantil', categoryLabel: 'Infantil', client: 'The Brands Club', title: '' },
  { id: 51, src: 'photos/infantil/01-2025-61.jpg', category: 'infantil', categoryLabel: 'Infantil', client: 'The Brands Club', title: '' },
  { id: 52, src: 'photos/infantil/01-2025-96.jpg', category: 'infantil', categoryLabel: 'Infantil', client: 'The Brands Club', title: '' },
  { id: 53, src: 'photos/infantil/01-2025-106.jpg', category: 'infantil', categoryLabel: 'Infantil', client: 'The Brands Club', title: '' },
  { id: 54, src: 'photos/infantil/01-2025-112.jpg', category: 'infantil', categoryLabel: 'Infantil', client: 'The Brands Club', title: '' },
  { id: 55, src: 'photos/infantil/01-2.jpg', category: 'infantil', categoryLabel: 'Infantil', client: 'The Brands Club', title: '' },
  { id: 56, src: 'photos/infantil/01-16.jpg', category: 'infantil', categoryLabel: 'Infantil', client: 'The Brands Club', title: '' },
  { id: 57, src: 'photos/infantil/01-49.jpg', category: 'infantil', categoryLabel: 'Infantil', client: 'The Brands Club', title: '' },
  { id: 58, src: 'photos/infantil/01-57.jpg', category: 'infantil', categoryLabel: 'Infantil', client: 'The Brands Club', title: '' },
  { id: 59, src: 'photos/infantil/01-63.jpg', category: 'infantil', categoryLabel: 'Infantil', client: 'The Brands Club', title: '' },
  { id: 62, src: 'photos/infantil/01-159.jpg', category: 'infantil', categoryLabel: 'Infantil', client: 'The Brands Club', title: '' },
  { id: 64, src: 'photos/infantil/01-204.jpg', category: 'infantil', categoryLabel: 'Infantil', client: 'The Brands Club', title: '' },
  { id: 66, src: 'photos/infantil/01-263.jpg', category: 'infantil', categoryLabel: 'Infantil', client: 'The Brands Club', title: '' },
  { id: 67, src: 'photos/infantil/01-274.jpg', category: 'infantil', categoryLabel: 'Infantil', client: 'The Brands Club', title: '' },
  { id: 68, src: 'photos/infantil/01-526.jpg', category: 'infantil', categoryLabel: 'Infantil', client: 'The Brands Club', title: '' },
  { id: 69, src: 'photos/infantil/02-2025-12.jpg', category: 'infantil', categoryLabel: 'Infantil', client: 'The Brands Club', title: '' },
  { id: 71, src: 'photos/infantil/02-2025-39.jpg', category: 'infantil', categoryLabel: 'Infantil', client: 'The Brands Club', title: '' },
  { id: 72, src: 'photos/infantil/03-2025-21.jpg', category: 'infantil', categoryLabel: 'Infantil', client: 'The Brands Club', title: '' },
  { id: 73, src: 'photos/infantil/03-2025-54.jpg', category: 'infantil', categoryLabel: 'Infantil', client: 'The Brands Club', title: '' },
  { id: 74, src: 'photos/infantil/03-2025-85.jpg', category: 'infantil', categoryLabel: 'Infantil', client: 'The Brands Club', title: '' },
  { id: 75, src: 'photos/infantil/03-2025-100.jpg', category: 'infantil', categoryLabel: 'Infantil', client: 'The Brands Club', title: '' },
  { id: 88, src: 'photos/infantil/3-en-1-2.jpg', category: 'infantil', categoryLabel: 'Infantil', client: 'Andes Gear', title: '' },
  { id: 89, src: 'photos/infantil/3-en-1-7.jpg', category: 'infantil', categoryLabel: 'Infantil', client: 'Andes Gear', title: '' },
  { id: 90, src: 'photos/infantil/3-en-1-9.jpg', category: 'infantil', categoryLabel: 'Infantil', client: 'Andes Gear', title: '' },
  { id: 91, src: 'photos/infantil/3-en-1-12.jpg', category: 'infantil', categoryLabel: 'Infantil', client: 'Andes Gear', title: '' },
  { id: 92, src: 'photos/infantil/3-en-1-14.jpg', category: 'infantil', categoryLabel: 'Infantil', client: 'Andes Gear', title: '' },
  { id: 93, src: 'photos/infantil/3-en-1-19.jpg', category: 'infantil', categoryLabel: 'Infantil', client: 'Andes Gear', title: '' },
  { id: 94, src: 'photos/infantil/3-en-1-24.jpg', category: 'infantil', categoryLabel: 'Infantil', client: 'Andes Gear', title: '' },
  { id: 95, src: 'photos/infantil/3-en-1-30.jpg', category: 'infantil', categoryLabel: 'Infantil', client: 'Andes Gear', title: '' },
  { id: 96, src: 'photos/infantil/3-en-1-35.jpg', category: 'infantil', categoryLabel: 'Infantil', client: 'Andes Gear', title: '' },
  { id: 97, src: 'photos/infantil/3-en-1-38.jpg', category: 'infantil', categoryLabel: 'Infantil', client: 'Andes Gear', title: '' },
  { id: 98, src: 'photos/infantil/3-en-1-43.jpg', category: 'infantil', categoryLabel: 'Infantil', client: 'Andes Gear', title: '' },
  { id: 99, src: 'photos/infantil/3-en-1-45.jpg', category: 'infantil', categoryLabel: 'Infantil', client: 'Andes Gear', title: '' },
  { id: 100, src: 'photos/infantil/3-en-1-49.jpg', category: 'infantil', categoryLabel: 'Infantil', client: 'Andes Gear', title: '' },
  { id: 108, src: 'photos/calzado/200027967182-1.jpg', category: 'calzado', categoryLabel: 'Calzado', client: 'Jarman', title: '' },
  { id: 113, src: 'photos/calzado/200027967199-2.jpg', category: 'calzado', categoryLabel: 'Calzado', client: 'Jarman', title: '' },
  { id: 119, src: 'photos/moda-mujer/1200139436568-9.jpg', category: 'moda-mujer', categoryLabel: 'Moda Mujer', client: 'Banana Republic', title: '' },
  { id: 121, src: 'photos/moda-mujer/1200139436568-22.jpg', category: 'moda-mujer', categoryLabel: 'Moda Mujer', client: 'Banana Republic', title: '' },
  { id: 123, src: 'photos/moda-mujer/1200140261760-10.jpg', category: 'moda-mujer', categoryLabel: 'Moda Mujer', client: 'Banana Republic', title: '' },
  { id: 124, src: 'photos/moda-mujer/1200140261760-20.jpg', category: 'moda-mujer', categoryLabel: 'Moda Mujer', client: 'Banana Republic', title: '' },
  { id: 125, src: 'photos/moda-mujer/1200140344876-14.jpg', category: 'moda-mujer', categoryLabel: 'Moda Mujer', client: 'Banana Republic', title: '' },
  { id: 127, src: 'photos/moda-mujer/1200140344876-23.jpg', category: 'moda-mujer', categoryLabel: 'Moda Mujer', client: 'Banana Republic', title: '' },
  { id: 130, src: 'photos/accesorios/1410621060052-3.jpg', category: 'accesorios', categoryLabel: 'Accesorios', client: 'Humana', title: '' },
  { id: 131, src: 'photos/accesorios/1410621060076-1.jpg', category: 'accesorios', categoryLabel: 'Accesorios', client: 'Humana', title: '' },
  { id: 132, src: 'photos/accesorios/1410621060076-2.jpg', category: 'accesorios', categoryLabel: 'Accesorios', client: 'Humana', title: '' },
  { id: 135, src: 'photos/calzado/2000391780633-3.jpg', category: 'calzado', categoryLabel: 'Calzado', client: 'Jarman', title: '' },
  { id: 140, src: 'photos/calzado/2000403275225-4.jpg', category: 'calzado', categoryLabel: 'Calzado', client: 'Jarman', title: '' },
  { id: 141, src: 'photos/moda-mujer/2017862201399-2.jpg', category: 'moda-mujer', categoryLabel: 'Moda Mujer', client: 'Be Active', title: '' },
  { id: 142, src: 'photos/moda-mujer/2017862201399-11.jpg', category: 'moda-mujer', categoryLabel: 'Moda Mujer', client: 'Be Active', title: '' },
  { id: 143, src: 'photos/moda-mujer/2017862201399-17.jpg', category: 'moda-mujer', categoryLabel: 'Moda Mujer', client: 'Be Active', title: '' },
  { id: 144, src: 'photos/moda-mujer/2017862201399-21.jpg', category: 'moda-mujer', categoryLabel: 'Moda Mujer', client: 'Be Active', title: '' },
  { id: 145, src: 'photos/moda-mujer/2017862201399-28.jpg', category: 'moda-mujer', categoryLabel: 'Moda Mujer', client: 'Be Active', title: '' },
  { id: 146, src: 'photos/accesorios/3102621880027-1.jpg', category: 'accesorios', categoryLabel: 'Accesorios', client: 'Tatienne', title: '' },
  { id: 147, src: 'photos/accesorios/3102621880034-1.jpg', category: 'accesorios', categoryLabel: 'Accesorios', client: 'Tatienne', title: '' },
  { id: 148, src: 'photos/accesorios/3307628000021-1.jpg', category: 'accesorios', categoryLabel: 'Accesorios', client: 'Tatienne', title: '' },
  { id: 149, src: 'photos/accesorios/3307628000021-3.jpg', category: 'accesorios', categoryLabel: 'Accesorios', client: 'Tatienne', title: '' },
  { id: 150, src: 'photos/accesorios/4307620200091-1.jpg', category: 'accesorios', categoryLabel: 'Accesorios', client: 'Tatienne', title: '' },
  { id: 151, src: 'photos/accesorios/5309614500025-2.jpg', category: 'accesorios', categoryLabel: 'Accesorios', client: 'Tatienne', title: '' },
  { id: 152, src: 'photos/accesorios/5318611540019-1.jpg', category: 'accesorios', categoryLabel: 'Accesorios', client: 'Tatienne', title: '' },
  { id: 153, src: 'photos/accesorios/5318611550018-2.jpg', category: 'accesorios', categoryLabel: 'Accesorios', client: 'Tatienne', title: '' },
  { id: 155, src: 'photos/accesorios/5318614500010-3.jpg', category: 'accesorios', categoryLabel: 'Accesorios', client: 'Tatienne', title: '' },
  { id: 158, src: 'photos/accesorios/5617614500021-2.jpg', category: 'accesorios', categoryLabel: 'Accesorios', client: 'Tatienne', title: '' },
  { id: 159, src: 'photos/moda-hombre/7804900024028-22.jpg', category: 'moda-hombre', categoryLabel: 'Moda Hombre', client: 'Buffalo', title: '' },
  { id: 160, src: 'photos/moda-hombre/7804900024622-16.jpg', category: 'moda-hombre', categoryLabel: 'Moda Hombre', client: 'Buffalo', title: '' },
  { id: 163, src: 'photos/moda-hombre/7804900022321-4.jpg', category: 'moda-hombre', categoryLabel: 'Moda Hombre', client: 'Buffalo', title: '' },
  { id: 164, src: 'photos/moda-hombre/7804900023120-12.jpg', category: 'moda-hombre', categoryLabel: 'Moda Hombre', client: 'Buffalo', title: '' },
  { id: 165, src: 'photos/moda-hombre/8893517388530-2.jpg', category: 'moda-hombre', categoryLabel: 'Moda Hombre', client: 'Andes Gear', title: '' },
  { id: 166, src: 'photos/moda-hombre/8893517388530-9.jpg', category: 'moda-hombre', categoryLabel: 'Moda Hombre', client: 'Andes Gear', title: '' },
  { id: 167, src: 'photos/moda-hombre/8893517388530-11.jpg', category: 'moda-hombre', categoryLabel: 'Moda Hombre', client: 'Andes Gear', title: '' },
  { id: 168, src: 'photos/moda-hombre/8893517388530-15.jpg', category: 'moda-hombre', categoryLabel: 'Moda Hombre', client: 'Andes Gear', title: '' },
  { id: 169, src: 'photos/moda-hombre/8893517388530-18.jpg', category: 'moda-hombre', categoryLabel: 'Moda Hombre', client: 'Andes Gear', title: '' },
  { id: 170, src: 'photos/moda-hombre/8893517388530-19.jpg', category: 'moda-hombre', categoryLabel: 'Moda Hombre', client: 'Andes Gear', title: '' },
  { id: 171, src: 'photos/moda-mujer/biker-01-1.jpg', category: 'moda-mujer', categoryLabel: 'Moda Mujer', client: 'Cova', title: '' },
  { id: 172, src: 'photos/moda-mujer/chaleco-cuello-02-17.jpg', category: 'moda-mujer', categoryLabel: 'Moda Mujer', client: 'Cova', title: '' },
  { id: 173, src: 'photos/moda-mujer/cow25-wjk11-35.jpg', category: 'moda-mujer', categoryLabel: 'Moda Mujer', client: 'Cova', title: '' },
  { id: 174, src: 'photos/moda-mujer/cow25-wjk12-24.jpg', category: 'moda-mujer', categoryLabel: 'Moda Mujer', client: 'Cova', title: '' },
  { id: 175, src: 'photos/moda-mujer/cow25-wpk09-20.jpg', category: 'moda-mujer', categoryLabel: 'Moda Mujer', client: 'Cova', title: '' },
  { id: 176, src: 'photos/campanias/31-de-julio-149.jpg', category: 'campanias', categoryLabel: 'Campañas', client: 'Flores', title: '' },
  { id: 177, src: 'photos/campanias/flores-189.jpg', category: 'campanias', categoryLabel: 'Campañas', client: 'Flores', title: '' },
  { id: 178, src: 'photos/campanias/fse189.jpg', category: 'campanias', categoryLabel: 'Campañas', client: 'Flores', title: '' },
  { id: 179, src: 'photos/flat-lay/2000403063044-1.jpg', category: 'flat-lay', categoryLabel: 'Flat Lay', client: 'Ripley', title: '' },
  { id: 180, src: 'photos/flat-lay/2000403063495-2.jpg', category: 'flat-lay', categoryLabel: 'Flat Lay', client: 'Ripley', title: '' },
  { id: 181, src: 'photos/flat-lay/2000403842700-1.jpg', category: 'flat-lay', categoryLabel: 'Flat Lay', client: 'Ripley', title: '' },
  { id: 182, src: 'photos/flat-lay/2000403878419-1.jpg', category: 'flat-lay', categoryLabel: 'Flat Lay', client: 'Ripley', title: '' },
  { id: 183, src: 'photos/flat-lay/2000403922594-1.jpg', category: 'flat-lay', categoryLabel: 'Flat Lay', client: 'Ripley', title: '' },
  { id: 184, src: 'photos/flat-lay/2000403936843-1.jpg', category: 'flat-lay', categoryLabel: 'Flat Lay', client: 'Ripley', title: '' },
  { id: 185, src: 'photos/flat-lay/2000403946682-2.jpg', category: 'flat-lay', categoryLabel: 'Flat Lay', client: 'Ripley', title: '' },
  { id: 186, src: 'photos/flat-lay/2000403954113-1.jpg', category: 'flat-lay', categoryLabel: 'Flat Lay', client: 'Ripley', title: '' },
  { id: 187, src: 'photos/flat-lay/2000403971776-1.jpg', category: 'flat-lay', categoryLabel: 'Flat Lay', client: 'Ripley', title: '' },
  { id: 188, src: 'photos/flat-lay/2000403971776-2.jpg', category: 'flat-lay', categoryLabel: 'Flat Lay', client: 'Ripley', title: '' },
  { id: 189, src: 'photos/flat-lay/2000403971776-3.jpg', category: 'flat-lay', categoryLabel: 'Flat Lay', client: 'Ripley', title: '' },
  { id: 190, src: 'photos/flat-lay/2000403971820-3.jpg', category: 'flat-lay', categoryLabel: 'Flat Lay', client: 'Ripley', title: '' },
  { id: 191, src: 'photos/flat-lay/2000404074926-1.jpg', category: 'flat-lay', categoryLabel: 'Flat Lay', client: 'Ripley', title: '' },
  { id: 192, src: 'photos/flat-lay/2000404074926-3.jpg', category: 'flat-lay', categoryLabel: 'Flat Lay', client: 'Ripley', title: '' },
  { id: 193, src: 'photos/campanias/fls18690-copia.jpg', category: 'campanias', categoryLabel: 'Campañas', client: 'Flores', title: '' },
  { id: 194, src: 'photos/campanias/fls18928-copia.jpg', category: 'campanias', categoryLabel: 'Campañas', client: 'Flores', title: '' },
  { id: 195, src: 'photos/campanias/fls19523-copia-1.jpg', category: 'campanias', categoryLabel: 'Campañas', client: 'Flores', title: '' },
  { id: 196, src: 'photos/360/eep-2100bl1.gif', category: '360', categoryLabel: '360°', client: 'Varios', title: '' },
  { id: 197, src: 'photos/360/nf00ce95agh-sm.gif', category: '360', categoryLabel: '360°', client: 'Varios', title: '' },
  { id: 198, src: 'photos/360/rosen-30.gif', category: '360', categoryLabel: '360°', client: 'Varios', title: '' },
  { id: 199, src: 'photos/360/rosen-34.gif', category: '360', categoryLabel: '360°', client: 'Varios', title: '' },
  { id: 200, src: 'photos/360/tc-2100v1.gif', category: '360', categoryLabel: '360°', client: 'Varios', title: '' },
  { id: 201, src: 'photos/moda-mujer/tenida-n-3-3.jpg', category: 'moda-mujer', categoryLabel: 'Moda Mujer', client: 'Be Active', title: '' },
  { id: 202, src: 'photos/moda-mujer/tenida-n-8-10.jpg', category: 'moda-mujer', categoryLabel: 'Moda Mujer', client: 'Be Active', title: '' },
  { id: 203, src: 'photos/accesorios/3308521100030-1.jpg', category: 'accesorios', categoryLabel: 'Accesorios', client: 'Humana', title: '' },
  { id: 204, src: 'photos/campanias/navidad-008-169.jpg', category: 'campanias', categoryLabel: 'Campañas', client: 'The Brands Club', title: '' },
  { id: 205, src: 'photos/calzado/p-338017983-1.jpg', category: 'calzado', categoryLabel: 'Calzado', client: 'The Brands Club', title: '' },
  { id: 206, src: 'photos/calzado/p-338017983-2.jpg', category: 'calzado', categoryLabel: 'Calzado', client: 'The Brands Club', title: '' },
  { id: 207, src: 'photos/calzado/p-338017983-3.jpg', category: 'calzado', categoryLabel: 'Calzado', client: 'The Brands Club', title: '' },
  { id: 208, src: 'photos/calzado/p-338017983-4.jpg', category: 'calzado', categoryLabel: 'Calzado', client: 'The Brands Club', title: '' },
  { id: 209, src: 'photos/infantil/tbc-of-02-167.jpg', category: 'infantil', categoryLabel: 'Infantil', client: 'The Brands Club', title: '' },
  { id: 210, src: 'photos/infantil/tbc-of-02-172.jpg', category: 'infantil', categoryLabel: 'Infantil', client: 'The Brands Club', title: '' },
  { id: 211, src: 'photos/infantil/tbc-of-04-100.jpg', category: 'infantil', categoryLabel: 'Infantil', client: 'The Brands Club', title: '' },
  { id: 212, src: 'photos/infantil/tbc-of-04-120.jpg', category: 'infantil', categoryLabel: 'Infantil', client: 'The Brands Club', title: '' },
  { id: 213, src: 'photos/colgados/p-314013785-3.jpg', category: 'colgados', categoryLabel: 'Colgados', client: 'The Brands Club', title: '' },
  { id: 214, src: 'photos/colgados/p-314013786-3.jpg', category: 'colgados', categoryLabel: 'Colgados', client: 'The Brands Club', title: '' },
  { id: 215, src: 'photos/colgados/p-315012654-3.jpg', category: 'colgados', categoryLabel: 'Colgados', client: 'The Brands Club', title: '' },
  { id: 216, src: 'photos/colgados/p-315012697-3.jpg', category: 'colgados', categoryLabel: 'Colgados', client: 'The Brands Club', title: '' },
  { id: 217, src: 'photos/colgados/p-315013604-3.jpg', category: 'colgados', categoryLabel: 'Colgados', client: 'The Brands Club', title: '' },
  { id: 218, src: 'photos/colgados/p-315013605-3.jpg', category: 'colgados', categoryLabel: 'Colgados', client: 'The Brands Club', title: '' },
  { id: 219, src: 'photos/colgados/p-315013605-4.jpg', category: 'colgados', categoryLabel: 'Colgados', client: 'The Brands Club', title: '' },
  { id: 220, src: 'photos/campanias/2025-08-12-tiendaflores-bano-00208.jpg', category: 'campanias', categoryLabel: 'Campañas', client: 'Flores', title: '' },
  { id: 221, src: 'photos/campanias/2025-08-12-tiendaflores-bano-00316.jpg', category: 'campanias', categoryLabel: 'Campañas', client: 'Flores', title: '' },
  { id: 222, src: 'photos/campanias/2025-08-12-tiendaflores-bano-00384.jpg', category: 'campanias', categoryLabel: 'Campañas', client: 'Flores', title: '' },
  { id: 223, src: 'photos/moda-hombre/2000404024624-2005.jpg', category: 'moda-hombre', categoryLabel: 'Moda Hombre', client: 'Ripley', title: '' },
  { id: 224, src: 'photos/moda-hombre/2000404212823-2134.jpg', category: 'moda-hombre', categoryLabel: 'Moda Hombre', client: 'Ripley', title: '' },
  { id: 225, src: 'photos/flat-lay/196780802726-1.jpg', category: 'flat-lay', categoryLabel: 'Flat Lay', client: 'Brooke Brothers', title: '' },
  { id: 226, src: 'photos/flat-lay/196780802726-2.jpg', category: 'flat-lay', categoryLabel: 'Flat Lay', client: 'Brooke Brothers', title: '' },
  { id: 227, src: 'photos/flat-lay/196780803471-1.jpg', category: 'flat-lay', categoryLabel: 'Flat Lay', client: 'Brooke Brothers', title: '' },
  { id: 228, src: 'photos/flat-lay/196780803471-2.jpg', category: 'flat-lay', categoryLabel: 'Flat Lay', client: 'Brooke Brothers', title: '' },
  { id: 229, src: 'photos/flat-lay/196780806694-1.jpg', category: 'flat-lay', categoryLabel: 'Flat Lay', client: 'Brooke Brothers', title: '' },
  { id: 230, src: 'photos/flat-lay/196780806694-2.jpg', category: 'flat-lay', categoryLabel: 'Flat Lay', client: 'Brooke Brothers', title: '' },
  { id: 231, src: 'photos/flat-lay/196780806915-1.jpg', category: 'flat-lay', categoryLabel: 'Flat Lay', client: 'Brooke Brothers', title: '' },
  { id: 232, src: 'photos/flat-lay/196780806915-2.jpg', category: 'flat-lay', categoryLabel: 'Flat Lay', client: 'Brooke Brothers', title: '' },
  { id: 233, src: 'photos/flat-lay/196780851076-1.jpg', category: 'flat-lay', categoryLabel: 'Flat Lay', client: 'Brooke Brothers', title: '' },
  { id: 234, src: 'photos/flat-lay/196780851076-2.jpg', category: 'flat-lay', categoryLabel: 'Flat Lay', client: 'Brooke Brothers', title: '' },
  { id: 235, src: 'photos/lenceria/25489-2-1.jpg', category: 'lenceria', categoryLabel: 'Lencería', client: 'Flores', title: '' },
  { id: 236, src: 'photos/lenceria/25502-235-1.jpg', category: 'lenceria', categoryLabel: 'Lencería', client: 'Flores', title: '' },
  { id: 237, src: 'photos/lenceria/90011-173-2.jpg', category: 'lenceria', categoryLabel: 'Lencería', client: 'Flores', title: '' },
  { id: 238, src: 'photos/accesorios/3617520200017-2.jpg', category: 'accesorios', categoryLabel: 'Accesorios', client: 'Humana', title: '' },
  { id: 239, src: 'photos/accesorios/3617520200031-1.jpg', category: 'accesorios', categoryLabel: 'Accesorios', client: 'Humana', title: '' },
  { id: 240, src: 'photos/accesorios/3617527900019-2.jpg', category: 'accesorios', categoryLabel: 'Accesorios', client: 'Humana', title: '' },
  { id: 241, src: 'photos/calzado/baker-caramelo-1.jpg', category: 'calzado', categoryLabel: 'Calzado', client: 'Antónima', title: '' },
  { id: 242, src: 'photos/calzado/baker-caramelo-2.jpg', category: 'calzado', categoryLabel: 'Calzado', client: 'Antónima', title: '' },
  { id: 243, src: 'photos/calzado/baker-caramelo-3.jpg', category: 'calzado', categoryLabel: 'Calzado', client: 'Antónima', title: '' },
  { id: 244, src: 'photos/calzado/baker-caramelo-4.jpg', category: 'calzado', categoryLabel: 'Calzado', client: 'Antónima', title: '' },
  { id: 245, src: 'photos/calzado/baker-caramelo-5.jpg', category: 'calzado', categoryLabel: 'Calzado', client: 'Antónima', title: '' },
  { id: 246, src: 'photos/calzado/taly-rojo-1.jpg', category: 'calzado', categoryLabel: 'Calzado', client: 'Antónima', title: '' },
  { id: 247, src: 'photos/calzado/taly-rojo-2.jpg', category: 'calzado', categoryLabel: 'Calzado', client: 'Antónima', title: '' },
  { id: 248, src: 'photos/calzado/taly-rojo-3.jpg', category: 'calzado', categoryLabel: 'Calzado', client: 'Antónima', title: '' },
  { id: 249, src: 'photos/calzado/taly-rojo-4.jpg', category: 'calzado', categoryLabel: 'Calzado', client: 'Antónima', title: '' },
  { id: 250, src: 'photos/calzado/taly-rojo-5.jpg', category: 'calzado', categoryLabel: 'Calzado', client: 'Antónima', title: '' },
  { id: 251, src: 'photos/accesorios/3309520200011-2.jpg', category: 'accesorios', categoryLabel: 'Accesorios', client: 'Humana', title: '' },
  { id: 252, src: 'photos/colgados/colgados-21.jpg', category: 'colgados', categoryLabel: 'Colgados', client: 'Raindoor', title: '' },
  { id: 253, src: 'photos/colgados/colgados-22.jpg', category: 'colgados', categoryLabel: 'Colgados', client: 'Raindoor', title: '' },
  { id: 254, src: 'photos/colgados/colgados-11.jpg', category: 'colgados', categoryLabel: 'Colgados', client: 'Raindoor', title: '' },
  { id: 255, src: 'photos/moda-mujer/chaqueta-metalizada-negra-3.jpg', category: 'moda-mujer', categoryLabel: 'Moda Mujer', client: 'Raindoor', title: '' },
  { id: 256, src: 'photos/moda-mujer/chaqueta-verde-matalizada-3.jpg', category: 'moda-mujer', categoryLabel: 'Moda Mujer', client: 'Raindoor', title: '' },
  { id: 257, src: 'photos/moda-mujer/cortes-tachas-2.jpg', category: 'moda-mujer', categoryLabel: 'Moda Mujer', client: 'Raindoor', title: '' },
  { id: 258, src: 'photos/moda-mujer/pantalon-lino-black-6.jpg', category: 'moda-mujer', categoryLabel: 'Moda Mujer', client: 'Raindoor', title: '' },
  { id: 259, src: 'photos/moda-mujer/pantes-flare-bolsillo-ecru-5.jpg', category: 'moda-mujer', categoryLabel: 'Moda Mujer', client: 'Raindoor', title: '' },
  { id: 260, src: 'photos/moda-mujer/pants-bag-blue-1.jpg', category: 'moda-mujer', categoryLabel: 'Moda Mujer', client: 'Raindoor', title: '' },
  { id: 261, src: 'photos/lenceria/25483-23-3.jpg', category: 'lenceria', categoryLabel: 'Lencería', client: 'Flores', title: '' },
];
