/* Foto Shop Estudio — data.js
   Generado desde el panel de administración */

const PHOTOS = [
  { id: 41, src: 'photos/lenceria/13273-241_1.jpg', category: 'lenceria', categoryLabel: 'Lencería', client: 'Flores', title: '' },
  { id: 42, src: 'photos/lenceria/25488-2-1.jpg', category: 'lenceria', categoryLabel: 'Lencería', client: 'Flores', title: '' },
  { id: 43, src: 'photos/lenceria/9683-1-5.jpg', category: 'lenceria', categoryLabel: 'Lencería', client: 'Flores', title: '' },
  { id: 44, src: 'photos/lenceria/9683-2-5.jpg', category: 'lenceria', categoryLabel: 'Lencería', client: 'Flores', title: '' },
  { id: 45, src: 'photos/lenceria/25486-2-1.jpg', category: 'lenceria', categoryLabel: 'Lencería', client: 'Flores', title: '' },
  { id: 46, src: 'photos/lenceria/90000-94-2.jpg', category: 'lenceria', categoryLabel: 'Lencería', client: 'Flores', title: '' },
  { id: 47, src: 'photos/lenceria/90003-1-3.jpg', category: 'lenceria', categoryLabel: 'Lencería', client: 'Flores', title: '' },
  { id: 48, src: 'photos/lenceria/grupo-ana-y-gaby-2.jpg', category: 'lenceria', categoryLabel: 'Lencería', client: 'Flores', title: '' },
  { id: 49, src: 'photos/lenceria/25511-172-1.jpg', category: 'lenceria', categoryLabel: 'Lencería', client: 'Flores', title: '' },
  { id: 50, src: 'photos/infantil/01-2025-14.jpg', category: 'infantil', categoryLabel: 'Infantil', client: 'The Brands Club', title: '' },
  { id: 51, src: 'photos/infantil/01-2025-61.jpg', category: 'infantil', categoryLabel: 'Infantil', client: 'The Brands Club', title: '' },
  { id: 52, src: 'photos/infantil/01-2025-96.jpg', category: 'infantil', categoryLabel: 'Infantil', client: 'The Brands Club', title: '' },
  { id: 53, src: 'photos/infantil/01-2025-106.jpg', category: 'infantil', categoryLabel: 'Infantil', client: 'The Brands Club', title: '' },
  { id: 54, src: 'photos/infantil/01-2025-112.jpg', category: 'infantil', categoryLabel: 'Infantil', client: 'The Brands Club', title: '' },
  { id: 55, src: 'photos/infantil/01-2.jpg', category: 'infantil', categoryLabel: 'Infantil', client: 'The Brands Club', title: '' },
  { id: 56, src: 'photos/infantil/01-16.jpg', category: 'infantil', categoryLabel: 'Infantil', client: 'The Brands Club', title: '' },
  { id: 57, src: 'photos/infantil/01-49.jpg', category: 'infantil', categoryLabel: 'Infantil', client: 'The Brands Club', title: '' },
  { id: 58, src: 'photos/infantil/01-57.jpg', category: 'infantil', categoryLabel: 'Infantil', client: 'The Brands Club', title: '' },
  { id: 59, src: 'photos/infantil/01-63.jpg', category: 'infantil', categoryLabel: 'Infantil', client: 'The Brands Club', title: '' },
  { id: 62, src: 'photos/infantil/01-159.jpg', category: 'infantil', categoryLabel: 'Infantil', client: 'The Brands Club', title: '' },
  { id: 64, src: 'photos/infantil/01-204.jpg', category: 'infantil', categoryLabel: 'Infantil', client: 'The Brands Club', title: '' },
  { id: 66, src: 'photos/infantil/01-263.jpg', category: 'infantil', categoryLabel: 'Infantil', client: 'The Brands Club', title: '' },
  { id: 67, src: 'photos/infantil/01-274.jpg', category: 'infantil', categoryLabel: 'Infantil', client: 'The Brands Club', title: '' },
  { id: 68, src: 'photos/infantil/01-526.jpg', category: 'infantil', categoryLabel: 'Infantil', client: 'The Brands Club', title: '' },
  { id: 69, src: 'photos/infantil/02-2025-12.jpg', category: 'infantil', categoryLabel: 'Infantil', client: 'The Brands Club', title: '' },
  { id: 71, src: 'photos/infantil/02-2025-39.jpg', category: 'infantil', categoryLabel: 'Infantil', client: 'The Brands Club', title: '' },
  { id: 72, src: 'photos/infantil/03-2025-21.jpg', category: 'infantil', categoryLabel: 'Infantil', client: 'The Brands Club', title: '' },
  { id: 73, src: 'photos/infantil/03-2025-54.jpg', category: 'infantil', categoryLabel: 'Infantil', client: 'The Brands Club', title: '' },
  { id: 74, src: 'photos/infantil/03-2025-85.jpg', category: 'infantil', categoryLabel: 'Infantil', client: 'The Brands Club', title: '' },
  { id: 75, src: 'photos/infantil/03-2025-100.jpg', category: 'infantil', categoryLabel: 'Infantil', client: 'The Brands Club', title: '' },
  { id: 88, src: 'photos/infantil/3-en-1-2.jpg', category: 'infantil', categoryLabel: 'Infantil', client: 'Andes Gear', title: '' },
  { id: 89, src: 'photos/infantil/3-en-1-7.jpg', category: 'infantil', categoryLabel: 'Infantil', client: 'Andes Gear', title: '' },
  { id: 90, src: 'photos/infantil/3-en-1-9.jpg', category: 'infantil', categoryLabel: 'Infantil', client: 'Andes Gear', title: '' },
  { id: 91, src: 'photos/infantil/3-en-1-12.jpg', category: 'infantil', categoryLabel: 'Infantil', client: 'Andes Gear', title: '' },
  { id: 92, src: 'photos/infantil/3-en-1-14.jpg', category: 'infantil', categoryLabel: 'Infantil', client: 'Andes Gear', title: '' },
  { id: 93, src: 'photos/infantil/3-en-1-19.jpg', category: 'infantil', categoryLabel: 'Infantil', client: 'Andes Gear', title: '' },
  { id: 94, src: 'photos/infantil/3-en-1-24.jpg', category: 'infantil', categoryLabel: 'Infantil', client: 'Andes Gear', title: '' },
  { id: 95, src: 'photos/infantil/3-en-1-30.jpg', category: 'infantil', categoryLabel: 'Infantil', client: 'Andes Gear', title: '' },
  { id: 96, src: 'photos/infantil/3-en-1-35.jpg', category: 'infantil', categoryLabel: 'Infantil', client: 'Andes Gear', title: '' },
  { id: 97, src: 'photos/infantil/3-en-1-38.jpg', category: 'infantil', categoryLabel: 'Infantil', client: 'Andes Gear', title: '' },
  { id: 98, src: 'photos/infantil/3-en-1-43.jpg', category: 'infantil', categoryLabel: 'Infantil', client: 'Andes Gear', title: '' },
  { id: 99, src: 'photos/infantil/3-en-1-45.jpg', category: 'infantil', categoryLabel: 'Infantil', client: 'Andes Gear', title: '' },
  { id: 100, src: 'photos/infantil/3-en-1-49.jpg', category: 'infantil', categoryLabel: 'Infantil', client: 'Andes Gear', title: '' },
  { id: 108, src: 'photos/calzado/200027967182-1.jpg', category: 'calzado', categoryLabel: 'Calzado', client: 'Jarman', title: '' },
  { id: 109, src: 'photos/calzado/200027967182-2.jpg', category: 'calzado', categoryLabel: 'Calzado', client: 'Jarman', title: '' },
  { id: 110, src: 'photos/calzado/200027967182-3.jpg', category: 'calzado', categoryLabel: 'Calzado', client: 'Jarman', title: '' },
  { id: 111, src: 'photos/calzado/200027967182-4.jpg', category: 'calzado', categoryLabel: 'Calzado', client: 'Jarman', title: '' },
  { id: 112, src: 'photos/calzado/200027967199-1.jpg', category: 'calzado', categoryLabel: 'Calzado', client: 'Jarman', title: '' },
  { id: 113, src: 'photos/calzado/200027967199-2.jpg', category: 'calzado', categoryLabel: 'Calzado', client: 'Jarman', title: '' },
  { id: 114, src: 'photos/calzado/200027967199-3.jpg', category: 'calzado', categoryLabel: 'Calzado', client: 'Jarman', title: '' },
  { id: 115, src: 'photos/calzado/200027967199-4.jpg', category: 'calzado', categoryLabel: 'Calzado', client: 'Jarman', title: '' },
  { id: 116, src: 'photos/moda-mujer/1200136972700-2.jpg', category: 'moda-mujer', categoryLabel: 'Moda Mujer', client: 'Banana Republic', title: '' },
  { id: 117, src: 'photos/moda-mujer/1200136972700-29.jpg', category: 'moda-mujer', categoryLabel: 'Moda Mujer', client: 'Banana Republic', title: '' },
  { id: 118, src: 'photos/moda-mujer/1200136972700-34.jpg', category: 'moda-mujer', categoryLabel: 'Moda Mujer', client: 'Banana Republic', title: '' },
  { id: 119, src: 'photos/moda-mujer/1200139436568-9.jpg', category: 'moda-mujer', categoryLabel: 'Moda Mujer', client: 'Banana Republic', title: '' },
  { id: 120, src: 'photos/moda-mujer/1200139436568-19.jpg', category: 'moda-mujer', categoryLabel: 'Moda Mujer', client: 'Banana Republic', title: '' },
  { id: 121, src: 'photos/moda-mujer/1200139436568-22.jpg', category: 'moda-mujer', categoryLabel: 'Moda Mujer', client: 'Banana Republic', title: '' },
  { id: 122, src: 'photos/moda-mujer/1200140261760-3.jpg', category: 'moda-mujer', categoryLabel: 'Moda Mujer', client: 'Banana Republic', title: '' },
  { id: 123, src: 'photos/moda-mujer/1200140261760-10.jpg', category: 'moda-mujer', categoryLabel: 'Moda Mujer', client: 'Banana Republic', title: '' },
  { id: 124, src: 'photos/moda-mujer/1200140261760-20.jpg', category: 'moda-mujer', categoryLabel: 'Moda Mujer', client: 'Banana Republic', title: '' },
  { id: 125, src: 'photos/moda-mujer/1200140344876-14.jpg', category: 'moda-mujer', categoryLabel: 'Moda Mujer', client: 'Banana Republic', title: '' },
  { id: 126, src: 'photos/moda-mujer/1200140344876-18.jpg', category: 'moda-mujer', categoryLabel: 'Moda Mujer', client: 'Banana Republic', title: '' },
  { id: 127, src: 'photos/moda-mujer/1200140344876-23.jpg', category: 'moda-mujer', categoryLabel: 'Moda Mujer', client: 'Banana Republic', title: '' },
  { id: 128, src: 'photos/accesorios/1410621060052-1.jpg', category: 'accesorios', categoryLabel: 'Accesorios', client: 'Humana', title: '' },
  { id: 129, src: 'photos/accesorios/1410621060052-2.jpg', category: 'accesorios', categoryLabel: 'Accesorios', client: 'Humana', title: '' },
  { id: 130, src: 'photos/accesorios/1410621060052-3.jpg', category: 'accesorios', categoryLabel: 'Accesorios', client: 'Humana', title: '' },
  { id: 131, src: 'photos/accesorios/1410621060076-1.jpg', category: 'accesorios', categoryLabel: 'Accesorios', client: 'Humana', title: '' },
  { id: 132, src: 'photos/accesorios/1410621060076-2.jpg', category: 'accesorios', categoryLabel: 'Accesorios', client: 'Humana', title: '' },
];
